apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    isDefault: false
    editable: true

  - name: PostgreSQL
    type: postgres
    uid: postgres
    url: postgres:5432
    database: fraud
    user: fraud
    secureJsonData:
      password: fraud
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true
